apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: python-demo-app
spec:
  type: LoadBalancer
  selector:
    name: python-pod
    app: python-demo-app
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
